### PR TITLE
Add compatibility for both Python 2 and Python 3

### PR DESCRIPTION
**Pull request by jonafato**
In trying to use [Hyde](/hyde/hyde) under Python 3, I ran into several
installation errors. This is the first of what will likely be a series of pull
requests to improve compatibility of Hyde-related libraries across
versions of Python.

In order to install fswrap under the current stable version of Python
(3.4.3), the following changes are needed:

- Conditionally redefine `unicode`, as it has been removed in Python 3
- Explicitly use `b''` when bytes are required
- Encode unicode strings before hashing

~~In addition to these changes, installation is upgraded to the current
version of distribute. distribute has been merged back into setuptools.
The current version simply wraps setuptools. distribute_setup.py and
distribute_setup.use_setuptools are removed to prevent old versions of
distribute from being installed over the current wrapper. This should be
considered a stopgap solution, and migrating to setuptools is highly
recommended.~~

Usage of distribute is replaced by setuptools.

Finally, tox is added to support testing under multiple versions of
Python. Test environments for latest stable versions of Python 2.7, 3.3,
and 3.4 are added.

Note: changes were made to satisfy all tests under all environments.
Test coverage is high (96% - 97%) depending on environment), but no
further use under Python 3 has been done so far.

### CODE REVIEW

**Comment by lakshmivyas** [comment]
Thanks so much @jonafato - Will merge this soon.

**Comment by jonafato** [comment]
@lakshmivyas This commit really includes two different changes, both of which fall under the umbrella of "modernization": upgrading to setuptools rather than a broken version of distribute and upgrading to support both Python 2 and Python 3. I'm happy to split the changes up into two pull requests if you'd like a cleaner commit history.

**Comment by lakshmivyas** [comment]
@jonafato - This looks good and works well as a single commit.   I will test this out tomorrow and merge.  Thank you.

**Comment by lakshmivyas** [comment]
@jonafato - Thank you :) :+1:

**Pull request merged**
